from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb://localhost:27017/")
db = client["tourism_recommender"]
collection = db["destinations"]

# Dictionary of destinations with just the best time to visit
best_times = {
    "Maldives": "November to April",
    "Paris": "June to August",
    "Bali": "April to October",
    "New York City": "April to June and September to early November",
    "Tokyo": "March to May and October to November",
    "Dubai": "November to March",
    "Rome": "April to June and September to October",
    "Sydney": "September to November and March to May",
    "Cape Town": "March to May and September to November",
    "Barcelona": "May to June and September",
    "London": "March to May",
    "Singapore": "February to April",
    "Istanbul": "April to May and September to mid-November",
    "Bangkok": "November to February",
    "Amsterdam": "April to May and September to November",
    "Prague": "May to September",
    "Los Angeles": "March to May and September to November",
    "San Francisco": "September to November",
    "Rio de Janeiro": "December to March",
    "Toronto": "Late April to May and September to October",
    "Vancouver": "March to May and September to November",
    "Honolulu": "April to October",
    "Athens": "March to May and September to November",
    "Venice": "September to November",
    "Florence": "May and September",
    "Marrakech": "March to May and September to November",
    "Lisbon": "March to May and September to October",
    "Vienna": "April to May and September to October",
    "Berlin": "May to September",
    "Hong Kong": "October to December",
    "Beijing": "March to May and September to October",
    "Shanghai": "October to November",
    "Seoul": "March to May and September to November",
    "Kyoto": "March to May and October to November",
    "Osaka": "March to May and October to November",
    "Mumbai": "October to February",
    "Delhi": "October to March",
    "Jaipur": "October to March",
    "Agra": "November to February",
    "Goa": "November to February",
    "Kerala": "September to March",
    "Leh-Ladakh": "May to September",
    "Manali": "October to February for snow, May to June for pleasant weather",
    "Darjeeling": "April to June and October to December",
    "Ooty": "October to June",
    "Mysore": "October to March",
    "Andaman and Nicobar Islands": "October to May",
    "Rishikesh": "September to November and February to May",
    "Amritsar": "October to March",
    "Shimla": "March to June and December to January for snowfall",
    "Varanasi": "November to February",
    "Kerala Backwaters": "October to March",
    "Jaipur": "October to March",
    "Ladakh": "May to September",
    "Varanasi": "October to March",
    "Andaman Islands": "October to May",
    "Darjeeling": "March to May and October to November",
    "Agra": "October to March",
    "Rishikesh": "September to November and March to May",
    "Mumbai": "November to February",
    "Udaipur": "October to March",
    "Hampi": "October to February",
    "Shimla": "March to June and December to February",
    "Delhi": "October to March",
    "Kanyakumari": "October to March",
    "Manali": "October to February and March to June",
    "Khajuraho": "October to March",
    "Pondicherry": "October to March",
    "Amritsar": "October to March",
    "Coorg": "October to March",
    "Jaisalmer": "October to March",
    "Kolkata": "October to March",
    "Mysore": "October to February",
    "Ooty": "April to June and September to November",
    "Rann of Kutch": "November to February",
    "Hyderabad": "October to February",
    "Srinagar": "April to October",
    "Ajanta Caves": "October to March",
    "Chennai": "November to February",
    "Gangtok": "March to June and September to November",
    "Madurai": "October to March",
    "Diu": "October to March",
    "Kochi": "October to March",
    "Kochi": "October to March",
    "Gir Forest": "December to March",
        "Bodh Gaya": "October to March",
        "Mandu": "July to February",
        "Dalhousie": "March to June and September to November",
        "Daman": "October to March",
        "Patnitop": "December to March",
        "Ranthambore": "October to April",
        "Gwalior": "October to March",
        "Mount Abu": "October to March",
        "Velankanni": "October to March",
        "Periyar": "October to February",
        "Orchha": "October to March",
        "Chandigarh": "October to March",
        "Kutch": "November to February",
        "Spiti Valley": "May to October",
        "Hazaribagh": "October to March",
        "Warangal": "October to March",
        "Kalimpong": "March to June and September to November",
        "Jabalpur": "October to March",
        "Dwarka": "October to March",
        "Panchgani": "September to May",
        "Kanpur": "October to March",
        "Bastar": "October to March",
        "Sarnath": "October to March",
        "Agartala": "October to April",
        "Chittorgarh": "October to March",
        "Almora": "April to June and September to November",
        "Bundi": "October to March"
}

# Update the best_time field for each destination
for name, best_time in best_times.items():
    result = collection.update_one(
        {"name": name},
        {"$set": {"best_time": best_time}}
    )
    if result.matched_count:
        print(f"Updated best time for: {name}")
    else:
        print(f"Destination not found: {name}")
