from pymongo import MongoClient

# MongoDB connection
client = MongoClient("mongodb://localhost:27017/")
db = client["tourism_recommender"]  # Matches the database from app.py
collection = db["destinations"]

# List of destinations with primary category, additional attributes, and image files
destinations = [
    {"name": "Maldives", "category": "Beach", "location": "Maldives", "description": "A tropical paradise with crystal-clear waters.", "attributes": ["Beach"], "image_file": "maldives.jpg"},
    {"name": "Goa", "category": "Beach", "location": "India", "description": "Famous for its beaches and vibrant nightlife.", "attributes": ["Beach", "City"], "image_file": "goa.jpeg"},
    {"name": "Swiss Alps", "category": "Mountain", "location": "Switzerland", "description": "A stunning range for skiing and hiking.", "attributes": ["Mountain"], "image_file": "swiss_alps.jpg"},
    {"name": "Himalayas", "category": "Mountain", "location": "India", "description": "Majestic peaks with spiritual significance.", "attributes": ["Mountain", "History"], "image_file": "himalayas.jpg"},
    {"name": "Paris", "category": "City", "location": "France", "description": "The city of love with iconic landmarks.", "attributes": ["City", "History"], "image_file": "paris.jpg"},
    {"name": "Tokyo", "category": "City", "location": "Japan", "description": "A blend of tradition and modernity.", "attributes": ["City", "History"], "image_file": "tokyo.jpg"},
    {"name": "Machu Picchu", "category": "History", "location": "Peru", "description": "An ancient Incan city in the mountains.", "attributes": ["History", "Mountain"], "image_file": "machu_picchu.jpg"},
    {"name": "Rome", "category": "History", "location": "Italy", "description": "A city rich in ancient ruins and culture.", "attributes": ["History", "City"], "image_file": "rome.jpeg"},
    {"name": "Santorini", "category": "Beach", "location": "Greece", "description": "White-washed buildings and stunning beaches.", "attributes": ["Beach", "History"], "image_file": "santorini.jpeg"},
    {"name": "New York City", "category": "City", "location": "USA", "description": "The Big Apple with skyscrapers and culture.", "attributes": ["City"], "image_file": "new_york_city.jpeg"},
    {"name": "Bali", "category": "Beach", "location": "Indonesia", "description": "A tropical island with beaches and temples.", "attributes": ["Beach", "History"], "image_file": "bali.jpeg"},
    {"name": "Banff", "category": "Mountain", "location": "Canada", "description": "Scenic mountains and turquoise lakes.", "attributes": ["Mountain"], "image_file": "banff.jpeg"},
    {"name": "London", "category": "City", "location": "UK", "description": "A historic city with modern attractions.", "attributes": ["City", "History"], "image_file": "london.jpeg"},
    {"name": "Cairo", "category": "History", "location": "Egypt", "description": "Home to the Pyramids and ancient wonders.", "attributes": ["History", "City"], "image_file": "cairo.jpeg"},
    {"name": "Phuket", "category": "Beach", "location": "Thailand", "description": "Beautiful beaches and vibrant nightlife.", "attributes": ["Beach"], "image_file": "phuket.jpeg"},
    {"name": "Mount Kilimanjaro", "category": "Mountain", "location": "Tanzania", "description": "Africa’s highest peak.", "attributes": ["Mountain"], "image_file": "mount_kilimanjaro.jpeg"},
    {"name": "Sydney", "category": "City", "location": "Australia", "description": "Famous for its opera house and beaches.", "attributes": ["City", "Beach"], "image_file": "sydney.jpeg"},
    {"name": "Athens", "category": "History", "location": "Greece", "description": "The birthplace of democracy with ancient ruins.", "attributes": ["History", "City"], "image_file": "athens.jpeg"},
    {"name": "Hawaii", "category": "Beach", "location": "USA", "description": "Volcanic islands with stunning beaches.", "attributes": ["Beach", "Mountain"], "image_file": "hawaii.jpeg"},
    {"name": "Andes", "category": "Mountain", "location": "South America", "description": "A vast mountain range with rich history.", "attributes": ["Mountain", "History"], "image_file": "andes.jpeg"},
    {"name": "Barcelona", "category": "City", "location": "Spain", "description": "A vibrant city with beaches and architecture.", "attributes": ["City", "Beach", "History"], "image_file": "barcelona.jpeg"},
    {"name": "Petra", "category": "History", "location": "Jordan", "description": "A rock-carved ancient city.", "attributes": ["History"], "image_file": "petra.jpeg"},
    {"name": "Miami", "category": "Beach", "location": "USA", "description": "Sunny beaches and a lively urban scene.", "attributes": ["Beach", "City"], "image_file": "miami.jpeg"},
    {"name": "Rocky Mountains", "category": "Mountain", "location": "USA", "description": "Rugged peaks and outdoor adventures.", "attributes": ["Mountain"], "image_file": "rocky_mountains.jpeg"},
    {"name": "Istanbul", "category": "History", "location": "Turkey", "description": "A city bridging Europe and Asia.", "attributes": ["History", "City"], "image_file": "istanbul.jpeg"},
    {"name": "Dubai", "category": "City", "location": "UAE", "description": "A futuristic city with desert charm.", "attributes": ["City"], "image_file": "dubai.jpeg"},
    {"name": "Bora Bora", "category": "Beach", "location": "French Polynesia", "description": "A luxurious island getaway.", "attributes": ["Beach"], "image_file": "bora_bora.jpeg"},
    {"name": "Yosemite", "category": "Mountain", "location": "USA", "description": "Famous for its cliffs and waterfalls.", "attributes": ["Mountain"], "image_file": "yosemite.jpg"},
    {"name": "Kyoto", "category": "History", "location": "Japan", "description": "A city of temples and tradition.", "attributes": ["History", "City"], "image_file": "kyoto.jpeg"},
    {"name": "Cape Town", "category": "Beach", "location": "South Africa", "description": "Beaches with a stunning mountain backdrop.", "attributes": ["Beach", "Mountain", "City"], "image_file": "cape_town.jpeg"},
    {"name": "Venice", "category": "City", "location": "Italy", "description": "A city of canals and historic charm.", "attributes": ["City", "History"], "image_file": "venice.jpeg"},
    {"name": "Great Barrier Reef", "category": "Beach", "location": "Australia", "description": "A world-famous coral reef.", "attributes": ["Beach"], "image_file": "great_barrier_reef.jpeg"},
    {"name": "Mount Everest", "category": "Mountain", "location": "Nepal", "description": "The world’s highest peak.", "attributes": ["Mountain"], "image_file": "mount_everest.jpeg"},
    {"name": "Jerusalem", "category": "History", "location": "Israel", "description": "A city sacred to multiple religions.", "attributes": ["History", "City"], "image_file": "jerusalem.jpeg"},
    {"name": "Rio de Janeiro", "category": "Beach", "location": "Brazil", "description": "Famous for Copacabana and Carnival.", "attributes": ["Beach", "City"], "image_file": "rio_de_janeiro.jpg"},
    {"name": "Prague", "category": "History", "location": "Czech Republic", "description": "A fairy-tale city with historic charm.", "attributes": ["History", "City"], "image_file": "prague.jpeg"},
    {"name": "Seychelles", "category": "Beach", "location": "Seychelles", "description": "Pristine beaches and granite boulders.", "attributes": ["Beach"], "image_file": "seychelles.jpeg"},
    {"name": "Pyrenees", "category": "Mountain", "location": "Spain/France", "description": "A scenic range between two countries.", "attributes": ["Mountain"], "image_file": "pyrenees.jpeg"},
    {"name": "Shanghai", "category": "City", "location": "China", "description": "A modern metropolis with history.", "attributes": ["City", "History"], "image_file": "shanghai.jpeg"},
    {"name": "Angkor Wat", "category": "History", "location": "Cambodia", "description": "A massive temple complex.", "attributes": ["History"], "image_file": "angkor_wat.jpeg"},
    {"name": "Chichen Itza", "category": "History", "location": "Mexico", "description": "A major Mayan archaeological site.", "attributes": ["History"], "image_file": "chichen_itza.jpeg"},
    {"name": "Kerala Backwaters", "category": "Beach", "location": "India", "description": "A network of serene lagoons and canals.", "attributes": ["Beach", "Nature", "Relaxation", "Culture", "Wildlife"], "image_file": "kerala_backwaters.jpeg"},
    {"name": "Jaipur", "category": "City", "location": "India", "description": "The Pink City known for its royal palaces.", "attributes": ["City", "History", "Culture", "Architecture", "Shopping"], "image_file": "jaipur.jpeg"},
    {"name": "Ladakh", "category": "Mountain", "location": "India", "description": "A high-altitude desert with monasteries.", "attributes": ["Mountain", "Adventure", "Spirituality", "Nature", "Culture"], "image_file": "ladakh.jpeg"},
    {"name": "Varanasi", "category": "History", "location": "India", "description": "A spiritual city on the Ganges.", "attributes": ["History", "Spirituality", "City", "Culture", "River"], "image_file": "varanasi.jpeg"},
    {"name": "Andaman Islands", "category": "Beach", "location": "India", "description": "Pristine beaches and coral reefs.", "attributes": ["Beach", "Nature", "Adventure", "Wildlife", "Relaxation"], "image_file": "andaman_islands.jpeg"},
    {"name": "Darjeeling", "category": "Mountain", "location": "India", "description": "Famous for tea gardens and Himalayan views.", "attributes": ["Mountain", "Nature", "Culture", "Food", "Scenic"], "image_file": "darjeeling.jpeg"},
    {"name": "Agra", "category": "History", "location": "India", "description": "Home to the iconic Taj Mahal.", "attributes": ["History", "Architecture", "City", "Culture", "Romance"], "image_file": "agra.jpeg"},
    {"name": "Rishikesh", "category": "Mountain", "location": "India", "description": "A yoga and adventure hub by the Ganges.", "attributes": ["Mountain", "Spirituality", "Adventure", "River", "Nature"], "image_file": "rishikesh.jpeg"},
    {"name": "Mumbai", "category": "City", "location": "India", "description": "India’s financial capital with Bollywood charm.", "attributes": ["City", "Beach", "Culture", "Food", "Entertainment"], "image_file": "mumbai.jpeg"},
    {"name": "Udaipur", "category": "City", "location": "India", "description": "The city of lakes and palaces.", "attributes": ["City", "History", "Romance", "Architecture", "Lakes"], "image_file": "udaipur.jpeg"},
    {"name": "Hampi", "category": "History", "location": "India", "description": "Ruins of a medieval kingdom.", "attributes": ["History", "Architecture", "Culture", "Nature", "Adventure"], "image_file": "hampi.jpeg"},
    {"name": "Shimla", "category": "Mountain", "location": "India", "description": "A colonial hill station in the Himalayas.", "attributes": ["Mountain", "History", "Nature", "Scenic", "Relaxation"], "image_file": "shimla.jpeg"},
    {"name": "Delhi", "category": "City", "location": "India", "description": "India’s capital with a blend of old and new.", "attributes": ["City", "History", "Culture", "Food", "Shopping"], "image_file": "delhi.jpeg"},
    {"name": "Kanyakumari", "category": "Beach", "location": "India", "description": "The southernmost tip with ocean views.", "attributes": ["Beach", "Nature", "Spirituality", "Scenic", "Culture"], "image_file": "kanyakumari.jpeg"},
    {"name": "Manali", "category": "Mountain", "location": "India", "description": "A snowy retreat for adventure lovers.", "attributes": ["Mountain", "Adventure", "Nature", "Snow", "Relaxation"], "image_file": "manali.jpeg"},
    {"name": "Khajuraho", "category": "History", "location": "India", "description": "Famous for its erotic temple carvings.", "attributes": ["History", "Architecture", "Culture", "Art", "Spirituality"], "image_file": "khajuraho.jpeg"},
    {"name": "Pondicherry", "category": "Beach", "location": "India", "description": "A French colonial town by the sea.", "attributes": ["Beach", "History", "Culture", "Relaxation", "Architecture"], "image_file": "pondicherry.jpeg"},
    {"name": "Amritsar", "category": "City", "location": "India", "description": "Home to the Golden Temple.", "attributes": ["City", "Spirituality", "History", "Culture", "Food"], "image_file": "amritsar.jpeg"},
    {"name": "Coorg", "category": "Mountain", "location": "India", "description": "A coffee haven in the Western Ghats.", "attributes": ["Mountain", "Nature", "Food", "Relaxation", "Culture"], "image_file": "coorg.jpeg"},
    {"name": "Jaisalmer", "category": "History", "location": "India", "description": "The Golden City in the Thar Desert.", "attributes": ["History", "Architecture", "Desert", "Culture", "Adventure"], "image_file": "jaisalmer.jpeg"},
    {"name": "Kolkata", "category": "City", "location": "India", "description": "A cultural hub with colonial heritage.", "attributes": ["City", "History", "Culture", "Food", "Art"], "image_file": "kolkata.jpeg"},
    {"name": "Mysore", "category": "City", "location": "India", "description": "Known for its palace and sandalwood.", "attributes": ["City", "History", "Culture", "Architecture", "Shopping"], "image_file": "mysore.jpeg"},
    {"name": "Ooty", "category": "Mountain", "location": "India", "description": "A hill station in the Nilgiris.", "attributes": ["Mountain", "Nature", "Scenic", "Relaxation", "History"], "image_file": "ooty.jpeg"},
    {"name": "Rann of Kutch", "category": "Desert", "location": "India", "description": "A vast salt desert with a unique festival.", "attributes": ["Desert", "Nature", "Culture", "Adventure", "Scenic"], "image_file": "rann_of_kutch.jpeg"},
    {"name": "Hyderabad", "category": "City", "location": "India", "description": "A city of biryani and historic forts.", "attributes": ["City", "History", "Food", "Culture", "Architecture"], "image_file": "hyderabad.jpeg"},
    {"name": "Srinagar", "category": "Mountain", "location": "India", "description": "A paradise with lakes and gardens.", "attributes": ["Mountain", "Lakes", "Nature", "Culture", "Relaxation"], "image_file": "srinagar.jpeg"},
    {"name": "Ajanta Caves", "category": "History", "location": "India", "description": "Ancient rock-cut Buddhist caves.", "attributes": ["History", "Architecture", "Spirituality", "Art", "Nature"], "image_file": "ajanta_caves.jpeg"},
    {"name": "Chennai", "category": "City", "location": "India", "description": "A coastal city with temples and beaches.", "attributes": ["City", "Beach", "Culture", "History", "Food"], "image_file": "chennai.jpeg"},
    {"name": "Gangtok", "category": "Mountain", "location": "India", "description": "A Himalayan town with monasteries.", "attributes": ["Mountain", "Nature", "Spirituality", "Culture", "Scenic"], "image_file": "gangtok.jpeg"},
    {"name": "Madurai", "category": "History", "location": "India", "description": "Famous for the Meenakshi Temple.", "attributes": ["History", "Spirituality", "City", "Culture", "Architecture"], "image_file": "madurai.jpeg"},
    {"name": "Diu", "category": "Beach", "location": "India", "description": "A quiet island with Portuguese charm.", "attributes": ["Beach", "History", "Relaxation", "Culture", "Architecture"], "image_file": "diu.jpeg"},
    {"name": "Nainital", "category": "Mountain", "location": "India", "description": "A lake town in the Kumaon hills.", "attributes": ["Mountain", "Lakes", "Nature", "Relaxation", "Scenic"], "image_file": "nainital.jpeg"},
    {"name": "Bhopal", "category": "City", "location": "India", "description": "A city of lakes and historic sites.", "attributes": ["City", "History", "Lakes", "Culture", "Nature"], "image_file": "bhopal.jpeg"},
    {"name": "Ellora Caves", "category": "History", "location": "India", "description": "Rock-cut temples and monasteries.", "attributes": ["History", "Architecture", "Spirituality", "Art", "Culture"], "image_file": "ellora_caves.jpeg"},
    {"name": "Puri", "category": "Beach", "location": "India", "description": "A pilgrimage site with a sandy coast.", "attributes": ["Beach", "Spirituality", "Culture", "History", "Nature"], "image_file": "puri.jpeg"},
    {"name": "Auli", "category": "Mountain", "location": "India", "description": "A skiing destination in the Himalayas.", "attributes": ["Mountain", "Adventure", "Snow", "Nature", "Scenic"], "image_file": "auli.jpeg"},
    {"name": "Ahmedabad", "category": "City", "location": "India", "description": "A textile hub with historic architecture.", "attributes": ["City", "History", "Culture", "Shopping", "Architecture"], "image_file": "ahmedabad.jpeg"},
    {"name": "Konark", "category": "History", "location": "India", "description": "Home to the Sun Temple.", "attributes": ["History", "Architecture", "Spirituality", "Culture", "Beach"], "image_file": "konark.jpeg"},
    {"name": "Munnar", "category": "Mountain", "location": "India", "description": "A tea plantation hill station.", "attributes": ["Mountain", "Nature", "Food", "Relaxation", "Scenic"], "image_file": "munnar.jpeg"},
    {"name": "Bhubaneswar", "category": "City", "location": "India", "description": "A city of ancient temples.", "attributes": ["City", "History", "Spirituality", "Culture", "Architecture"], "image_file": "bhubaneswar.jpeg"},
    {"name": "Gulmarg", "category": "Mountain", "location": "India", "description": "A snowy paradise for skiing.", "attributes": ["Mountain", "Adventure", "Snow", "Nature", "Scenic"], "image_file": "gulmarg.jpeg"},
    {"name": "Jodhpur", "category": "City", "location": "India", "description": "The Blue City with a majestic fort.", "attributes": ["City", "History", "Architecture", "Culture", "Desert"], "image_file": "jodhpur.jpeg"},
    {"name": "Leh", "category": "Mountain", "location": "India", "description": "A high-altitude town with monasteries.", "attributes": ["Mountain", "Adventure", "Spirituality", "Culture", "Nature"], "image_file": "leh.jpeg"},
    {"name": "Kodaikanal", "category": "Mountain", "location": "India", "description": "A misty hill station with lakes.", "attributes": ["Mountain", "Nature", "Lakes", "Relaxation", "Scenic"], "image_file": "kodaikanal.jpeg"},
    {"name": "Gokarna", "category": "Beach", "location": "India", "description": "A quieter alternative to Goa.", "attributes": ["Beach", "Spirituality", "Nature", "Relaxation", "Culture"], "image_file": "gokarna.jpeg"},
    {"name": "Tirupati", "category": "History", "location": "India", "description": "A major pilgrimage site.", "attributes": ["History", "Spirituality", "Culture", "Architecture", "City"], "image_file": "tirupati.jpeg"},
    {"name": "Shillong", "category": "Mountain", "location": "India", "description": "The Scotland of the East.", "attributes": ["Mountain", "Nature", "Culture", "Scenic", "Relaxation"], "image_file": "shillong.jpeg"},
    {"name": "Sundarbans", "category": "Nature", "location": "India", "description": "A mangrove forest with Bengal tigers.", "attributes": ["Nature", "Wildlife", "Adventure", "River", "Culture"], "image_file": "sundarbans.jpeg"},
    {"name": "Bikaner", "category": "History", "location": "India", "description": "A desert city with forts and camels.", "attributes": ["History", "Desert", "Culture", "Architecture", "Adventure"], "image_file": "bikaner.jpeg"},
    {"name": "Haridwar", "category": "History", "location": "India", "description": "A holy city on the Ganges.", "attributes": ["History", "Spirituality", "River", "Culture", "City"], "image_file": "haridwar.jpeg"},
    {"name": "Tawang", "category": "Mountain", "location": "India", "description": "A remote town with a large monastery.", "attributes": ["Mountain", "Spirituality", "Nature", "Culture", "Scenic"], "image_file": "tawang.jpeg"},
    {"name": "Alleppey", "category": "Beach", "location": "India", "description": "Famous for houseboat cruises.", "attributes": ["Beach", "Nature", "Relaxation", "Culture", "River"], "image_file": "alleppey.jpeg"},
    {"name": "Pushkar", "category": "History", "location": "India", "description": "A sacred town with a desert fair.", "attributes": ["History", "Spirituality", "Culture", "Desert", "Adventure"], "image_file": "pushkar.jpeg"},
    {"name": "Dharamshala", "category": "Mountain", "location": "India", "description": "Home to the Dalai Lama.", "attributes": ["Mountain", "Spirituality", "Nature", "Culture", "Scenic"], "image_file": "dharamshala.jpeg"},
    {"name": "Lucknow", "category": "City", "location": "India", "description": "A city of kebabs and nawabi culture.", "attributes": ["City", "History", "Food", "Culture", "Architecture"], "image_file": "lucknow.jpeg"},
    {"name": "Mahabalipuram", "category": "Beach", "location": "India", "description": "Ancient rock-cut temples by the sea.", "attributes": ["Beach", "History", "Architecture", "Culture", "Spirituality"], "image_file": "mahabalipuram.jpeg"},
    {"name": "Mussoorie", "category": "Mountain", "location": "India", "description": "The Queen of Hills.", "attributes": ["Mountain", "Nature", "Scenic", "Relaxation", "History"], "image_file": "mussoorie.jpeg"},
    {"name": "Guwahati", "category": "City", "location": "India", "description": "Gateway to Northeast India.", "attributes": ["City", "River", "Culture", "Nature", "Spirituality"], "image_file": "guwahati.jpeg"},
    {"name": "Sanchi", "category": "History", "location": "India", "description": "Ancient Buddhist stupas.", "attributes": ["History", "Spirituality", "Architecture", "Culture", "Nature"], "image_file": "sanchi.jpeg"},
    {"name": "Varkala", "category": "Beach", "location": "India", "description": "A cliffside beach with springs.", "attributes": ["Beach", "Nature", "Relaxation", "Spirituality", "Scenic"], "image_file": "varkala.jpeg"},
    {"name": "Pune", "category": "City", "location": "India", "description": "A blend of history and modernity.", "attributes": ["City", "History", "Culture", "Education", "Food"], "image_file": "pune.jpeg"},
    {"name": "Kaziranga", "category": "Nature", "location": "India", "description": "Home to the one-horned rhino.", "attributes": ["Nature", "Wildlife", "Adventure", "River", "Scenic"], "image_file": "kaziranga.jpeg"},
    {"name": "Badami", "category": "History", "location": "India", "description": "Rock-cut caves and temples.", "attributes": ["History", "Architecture", "Spirituality", "Culture", "Nature"], "image_file": "badami.jpeg"},
    {"name": "Cherrapunji", "category": "Mountain", "location": "India", "description": "One of the wettest places on Earth.", "attributes": ["Mountain", "Nature", "Waterfalls", "Scenic", "Adventure"], "image_file": "cherrapunji.jpeg"},
    {"name": "Nagpur", "category": "City", "location": "India", "description": "The orange city with lakes.", "attributes": ["City", "Nature", "Food", "Culture", "Lakes"], "image_file": "nagpur.jpeg"},
    {"name": "Thanjavur", "category": "History", "location": "India", "description": "Famous for its Brihadeeswarar Temple.", "attributes": ["History", "Architecture", "Spirituality", "Culture", "City"], "image_file": "thanjavur.jpeg"},
    {"name": "Lonavala", "category": "Mountain", "location": "India", "description": "A hill station with waterfalls.", "attributes": ["Mountain", "Nature", "Waterfalls", "Relaxation", "Scenic"], "image_file": "lonavala.jpeg"},
    {"name": "Kochi", "category": "City", "location": "India", "description": "A port city with colonial history.", "attributes": ["City", "Beach", "History", "Culture", "Food"], "image_file": "kochi.jpeg"},
    {"name": "Gir Forest", "category": "Nature", "location": "India", "description": "Home to the Asiatic lion.", "attributes": ["Nature", "Wildlife", "Adventure", "Forest", "Culture"], "image_file": "gir_forest.jpeg"},
    {"name": "Bodh Gaya", "category": "History", "location": "India", "description": "Where Buddha attained enlightenment.", "attributes": ["History", "Spirituality", "Culture", "Nature", "Architecture"], "image_file": "bodh_gaya.jpeg"},
    {"name": "Mandu", "category": "History", "location": "India", "description": "A ruined hilltop fortress.", "attributes": ["History", "Architecture", "Nature", "Culture", "Adventure"], "image_file": "mandu.jpeg"},
    {"name": "Dalhousie", "category": "Mountain", "location": "India", "description": "A colonial hill station.", "attributes": ["Mountain", "Nature", "History", "Relaxation", "Scenic"], "image_file": "dalhousie.jpeg"},
    {"name": "Daman", "category": "Beach", "location": "India", "description": "A coastal retreat with Portuguese influence.", "attributes": ["Beach", "History", "Relaxation", "Culture", "Architecture"], "image_file": "daman.jpeg"},
    {"name": "Patnitop", "category": "Mountain", "location": "India", "description": "A snowy hill station in Jammu.", "attributes": ["Mountain", "Snow", "Nature", "Adventure", "Scenic"], "image_file": "patnitop.jpeg"},
    {"name": "Ranthambore", "category": "Nature", "location": "India", "description": "A tiger reserve with historic forts.", "attributes": ["Nature", "Wildlife", "Adventure", "History", "Culture"], "image_file": "ranthambore.jpeg"},
    {"name": "Gwalior", "category": "City", "location": "India", "description": "A city with a grand hilltop fort.", "attributes": ["City", "History", "Architecture", "Culture", "Music"], "image_file": "gwalior.jpeg"},
    {"name": "Mount Abu", "category": "Mountain", "location": "India", "description": "Rajasthan’s only hill station.", "attributes": ["Mountain", "Nature", "Spirituality", "Relaxation", "Scenic"], "image_file": "mount_abu.jpeg"},
    {"name": "Velankanni", "category": "Beach", "location": "India", "description": "A pilgrimage site with a basilica.", "attributes": ["Beach", "Spirituality", "Culture", "History", "Relaxation"], "image_file": "velankanni.jpeg"},
    {"name": "Periyar", "category": "Nature", "location": "India", "description": "A wildlife sanctuary with a lake.", "attributes": ["Nature", "Wildlife", "Lakes", "Adventure", "Scenic"], "image_file": "periyar.jpeg"},
    {"name": "Orchha", "category": "History", "location": "India", "description": "A medieval town with palaces.", "attributes": ["History", "Architecture", "Culture", "Nature", "River"], "image_file": "orchha.jpeg"},
    {"name": "Chandigarh", "category": "City", "location": "India", "description": "A planned city with modern design.", "attributes": ["City", "Architecture", "Culture", "Nature", "Shopping"], "image_file": "chandigarh.jpeg"},
    {"name": "Kutch", "category": "Desert", "location": "India", "description": "A vast desert with handicraft villages.", "attributes": ["Desert", "Culture", "Nature", "Adventure", "Shopping"], "image_file": "kutch.jpeg"},
    {"name": "Spiti Valley", "category": "Mountain", "location": "India", "description": "A cold desert with ancient monasteries.", "attributes": ["Mountain", "Adventure", "Spirituality", "Nature", "Culture"], "image_file": "spiti_valley.jpeg"},
    {"name": "Hazaribagh", "category": "Nature", "location": "India", "description": "A forested area with waterfalls.", "attributes": ["Nature", "Wildlife", "Waterfalls", "Adventure", "Scenic"], "image_file": "hazaribagh.jpeg"},
    {"name": "Warangal", "category": "History", "location": "India", "description": "A city with ancient temples and forts.", "attributes": ["History", "Architecture", "Culture", "City", "Spirituality"], "image_file": "warangal.jpeg"},
    {"name": "Kalimpong", "category": "Mountain", "location": "India", "description": "A quiet hill town with monasteries.", "attributes": ["Mountain", "Nature", "Spirituality", "Relaxation", "Scenic"], "image_file": "kalimpong.jpeg"},
    {"name": "Jabalpur", "category": "City", "location": "India", "description": "Famous for marble rocks and waterfalls.", "attributes": ["City", "Nature", "Waterfalls", "Adventure", "Scenic"], "image_file": "jabalpur.jpeg"},
    {"name": "Dwarka", "category": "History", "location": "India", "description": "An ancient city tied to Lord Krishna.", "attributes": ["History", "Spirituality", "Beach", "Culture", "Architecture"], "image_file": "dwarka.jpeg"},
    {"name": "Panchgani", "category": "Mountain", "location": "India", "description": "A hill station with strawberry farms.", "attributes": ["Mountain", "Nature", "Food", "Relaxation", "Scenic"], "image_file": "panchgani.jpeg"},
    {"name": "Kanpur", "category": "City", "location": "India", "description": "An industrial city with historic sites.", "attributes": ["City", "History", "Culture", "River", "Shopping"], "image_file": "kanpur.jpeg"},
    {"name": "Bastar", "category": "Nature", "location": "India", "description": "A tribal region with forests and waterfalls.", "attributes": ["Nature", "Culture", "Wildlife", "Adventure", "Waterfalls"], "image_file": "bastar.jpeg"},
    {"name": "Sarnath", "category": "History", "location": "India", "description": "A Buddhist pilgrimage site near Varanasi.", "attributes": ["History", "Spirituality", "Culture", "Architecture", "Nature"], "image_file": "sarnath.jpeg"},
    {"name": "Agartala", "category": "City", "location": "India", "description": "A cultural hub in the Northeast.", "attributes": ["City", "Culture", "History", "Nature", "Shopping"], "image_file": "agartala.jpeg"},
    {"name": "Chittorgarh", "category": "History", "location": "India", "description": "A historic fort with tales of valor.", "attributes": ["History", "Architecture", "Culture", "Adventure", "Scenic"], "image_file": "chittorgarh.jpeg"},
    {"name": "Almora", "category": "Mountain", "location": "India", "description": "A peaceful Himalayan town.", "attributes": ["Mountain", "Nature", "Relaxation", "Culture", "Scenic"], "image_file": "almora.jpeg"},
    {"name": "Bundi", "category": "History", "location": "India", "description": "A small town with forts and stepwells.", "attributes": ["History", "Architecture", "Culture", "Nature", "Adventure"], "image_file": "bundi.jpeg"}
]

# Optional: clear the old data in the collection
collection.delete_many({})

# Insert into MongoDB
collection.insert_many(destinations)

print("✅ Inserted destinations into 'tourism_recommender' with lowercase image files in .jpeg format!")